activeThreshold=2  # 词节点的可激活阈值
minactive=3  # 备选词最低激活值
LPminactive=20 # 在规划求解中使用的带余地的激活阈值
minp=10000  # 备选句子最低生成概率（使用权值均值）
minstop=0.2  # 舍弃停用词的概率
stackWeights=0.9 # 叠加接边衰减
repeatLimit=1 # 生成实词的重复次数限制
maxLength=40 # 生成的句子的最大长度
topicTolerance=5 # 允许概率低于最低生成概率的最大句子长度
initActivation=6 # 初激活值
selectActivation=50 # 选取摘要块序列的活跃度参数，越大越倾向于选择概率小的

simThreshold=0.85 # 句子被视为相似的阈值
activeThresholdB=2  # 块节点的可激活阈值
minactiveB=3  # 备选块最低激活值
minpB=1  # 备选块序列最低生成概率（未使用权值均值）
stackWeightsB=0.9 # 叠加接边衰减
maxLengthB=1000 # 篇章最大句子数
topicToleranceB=5 # 允许概率低于最低生成概率的最大篇章长度
radomWeight = False # wordmap未训练权值是否随机
simMergers = False # 对相似句子计数并自动合并相似句子的接边。训练集量小时无效。关闭视所有句子都不相似，pnBlock接边仅按训练集序